// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoRequest struct {
	UserId int64 `json:"userId"`
}

type UserUpdateRequest struct {
	UserId int64 `json:"userId"`
}

type UserInfoResponse struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
}

type UserUpdateResponse struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
}
